language: ruby
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
before_install: "gem install bundler:1.17.2"
cache: bundler
script: "bundle exec rake test"
notifications:
  email: false
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6_edge.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6_edge.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6_edge.gemfile
